version: '3.8'

services:
  frontend:
   build:
      context: ./front
      dockerfile: Dockerfile  
   ports:
      - "8080:80"
   networks:
      - my_network

  #api:
  #  build:
  #     context: ./api
  #     dockerfile: Dockerfile 
  # ports:
  #    - "5000:5000"
  #  networks:
  #     - my_network

  db:
    image: postgres:13  
    environment:
      POSTGRES_USER: user      
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: mydb        
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - my_network   
    restart: always  
    ports:
      - "5432:5432"  # Expose le port PostgreSQL à l'extérieur pour permettre les connexions externes

  adminer:
    image: adminer 
    ports:
      - "8081:8080" 
    networks:
      - my_network  
    environment:
      ADMINER_DEFAULT_SERVER: db  
      ADMINER_THEME: dracula

networks:
  my_network: 

volumes:
  postgres-data:
